# See full settings at https://github.com/golangci/golangci-lint
run:
  concurrency: 4
  timeout: 3m
  tests: false
issues:
  exclude-dirs:
    - dist
    - docs
    - .github
    - playground

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - dogsled
      #- dupl disable, because parser and lexer may have similer logic
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
      #- gomnd
    - lll
    - misspell
    - whitespace
    - unparam
  fast: false

linters-settings:
  dogsled:
    max-blank-identifiers: 2
  dupl:
    threshold: 200
  errcheck:
    check-type-assertions: true
    check-blank: true
  funlen:
    lines: 200
    statements: 100
  gocognit:
    min-complexity: 50
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    settings:
      nestingReduce:
        bodyWidth: 3
      rangeValCopy:
        sizeThreshold: 2048

    #see: https://go-critic.github.io/overview#checks-overview
    enabled-checks:
      - boolExprSimplify
      - builtinShadow
      - emptyFallthrough
      - emptyStringTest
      - equalFold
      - evalOrder
      - importShadow
      - indexAlloc
      - initClause
      - methodExprCall
      - nestingReduce
      - nilValReturn
      - octalLiteral
      - paramTypeCombine
      - ptrToRefParam
      - rangeExprCopy
      - rangeValCopy
      - regexpPattern
      - sloppyReassign
      - stringXbytes
      - truncateCmp
      - typeAssertChain
      - typeUnparen
      - unlabelStmt
      - unnecessaryBlock
      - weakCond
      - yodaStyleExpr
  gocyclo:
    min-complexity: 50
  gofmt:
    simplify: true
  lll:
    line-length: 150
  misspell:
    locale: US
    ignore-words:
      - sponser
  whitespace:
    multi-if: true
    multi-func: true
