// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"testing"

	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/value"
)

// Fastly built-in function testing implementation of accept.charset_lookup
// Arguments may be:
// - STRING, STRING, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/content-negotiation/accept-charset-lookup/
func Test_Accept_charset_lookup(t *testing.T) {

	ret, err := Accept_charset_lookup(
		&context.Context{},
		&value.String{Value: "iso-8859-5:iso-8859-2"},
		&value.String{Value: "utf-8"},
		&value.String{Value: "utf-8, iso-8859-1;q=0.5, *;q=0.1"},
	)
	if err != nil {
		t.Errorf("Unexpected error: %s", err)
	}
	if ret.Type() != value.StringType {
		t.Errorf("Unexpected type returned, expect=%s, got=%s", value.StringType, ret.Type())
	}
	v := value.Unwrap[*value.String](ret)
	if v.Value != "utf-8" {
		t.Errorf("Unexpected value returned, expect=utf-8, got=%s", v.Value)
	}
}
