// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

var Bin_base64_to_hex_ArgumentTypes = []value.Type{value.StringType}

func Bin_base64_to_hex_Validate(args []value.Value) error {
	if len(args) != 1 {
		return errors.ArgumentNotEnough("bin.base64_to_hex", 1, args)
	}
	for i := range args {
		if args[i].Type() != Bin_base64_to_hex_ArgumentTypes[i] {
			return errors.TypeMismatch("bin.base64_to_hex", i+1, Bin_base64_to_hex_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of bin.base64_to_hex
// Arguments may be:
// - STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/cryptographic/bin-base64-to-hex/
func Bin_base64_to_hex(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Bin_base64_to_hex_Validate(args); err != nil {
		return value.Null, err
	}

	// Need to be implemented
	return value.Null, errors.NotImplemented("bin.base64_to_hex")
}
