// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"testing"
	// "github.com/ysugimoto/falco/interpreter/context"
	// "github.com/ysugimoto/falco/interpreter/value"
)

// Fastly built-in function testing implementation of boltsort.sort
// Arguments may be:
// - STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/query-string/boltsort-sort/
func Test_Boltsort_sort(t *testing.T) {
	t.Skip("Test Builtin function boltsort.sort should be impelemented")
}
