// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"encoding/base64"

	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/function/shared"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Crypto_decrypt_base64_Name = "crypto.decrypt_base64"

var Crypto_decrypt_base64_ArgumentTypes = []value.Type{value.IdentType, value.IdentType, value.IdentType, value.StringType, value.StringType, value.StringType}

func Crypto_decrypt_base64_Validate(args []value.Value) error {
	if len(args) != 6 {
		return errors.ArgumentNotEnough(Crypto_decrypt_base64_Name, 6, args)
	}
	for i := range args {
		if args[i].Type() != Crypto_decrypt_base64_ArgumentTypes[i] {
			return errors.TypeMismatch(Crypto_decrypt_base64_Name, i+1, Crypto_decrypt_base64_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of crypto.decrypt_base64
// Arguments may be:
// - ID, ID, ID, STRING, STRING, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/cryptographic/crypto-decrypt-base64/
func Crypto_decrypt_base64(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Crypto_decrypt_base64_Validate(args); err != nil {
		return value.Null, err
	}

	cipherId := value.Unwrap[*value.Ident](args[0])
	mode := value.Unwrap[*value.Ident](args[1])
	padding := value.Unwrap[*value.Ident](args[2])
	key := value.Unwrap[*value.String](args[3])
	iv := value.Unwrap[*value.String](args[4])
	text := value.Unwrap[*value.String](args[5])

	buf, err := base64.StdEncoding.DecodeString(text.Value)
	if err != nil {
		return value.Null, errors.New("Failed to decode base64 encoded string: %s", text.Value)
	}

	codec, err := shared.NewCryptoCodec(
		Crypto_decrypt_base64_Name,
		cipherId.Value, mode.Value, padding.Value,
	)
	if err != nil {
		return value.Null, err
	}

	decrypted, err := codec.Decrypt(key.Value, iv.Value, buf)
	if err != nil {
		return value.Null, err
	}

	return &value.String{
		Value: base64.StdEncoding.EncodeToString(decrypted),
	}, nil
}
