// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"encoding/hex"

	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/function/shared"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Crypto_decrypt_hex_Name = "crypto.decrypt_hex"

var Crypto_decrypt_hex_ArgumentTypes = []value.Type{value.IdentType, value.IdentType, value.IdentType, value.StringType, value.StringType, value.StringType}

func Crypto_decrypt_hex_Validate(args []value.Value) error {
	if len(args) != 6 {
		return errors.ArgumentNotEnough(Crypto_decrypt_hex_Name, 6, args)
	}
	for i := range args {
		if args[i].Type() != Crypto_decrypt_hex_ArgumentTypes[i] {
			return errors.TypeMismatch(Crypto_decrypt_hex_Name, i+1, Crypto_decrypt_hex_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of crypto.decrypt_hex
// Arguments may be:
// - ID, ID, ID, STRING, STRING, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/cryptographic/crypto-decrypt-hex/
func Crypto_decrypt_hex(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Crypto_decrypt_hex_Validate(args); err != nil {
		return value.Null, err
	}

	cipherId := value.Unwrap[*value.Ident](args[0])
	mode := value.Unwrap[*value.Ident](args[1])
	padding := value.Unwrap[*value.Ident](args[2])
	key := value.GetString(args[3]).String()
	iv := value.GetString(args[4]).String()
	text := value.GetString(args[5]).String()

	buf, err := hex.DecodeString(text)
	if err != nil {
		return value.Null, errors.New("Failed to decode hex string: %s", text)
	}

	codec, err := shared.NewCryptoCodec(
		Crypto_decrypt_hex_Name,
		cipherId.Value, mode.Value, padding.Value,
	)
	if err != nil {
		return value.Null, err
	}

	decrypted, err := codec.Decrypt(key, iv, buf)
	if err != nil {
		return value.Null, err
	}

	return &value.String{Value: hex.EncodeToString(decrypted)}, nil
}
