// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

var Crypto_encrypt_hex_ArgumentTypes = []value.Type{value.IdentType, value.IdentType, value.IdentType, value.StringType, value.StringType, value.StringType}

func Crypto_encrypt_hex_Validate(args []value.Value) error {
	if len(args) != 6 {
		return errors.ArgumentNotEnough("crypto.encrypt_hex", 6, args)
	}
	for i := range args {
		if args[i].Type() != Crypto_encrypt_hex_ArgumentTypes[i] {
			return errors.TypeMismatch("crypto.encrypt_hex", i+1, Crypto_encrypt_hex_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of crypto.encrypt_hex
// Arguments may be:
// - ID, ID, ID, STRING, STRING, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/cryptographic/crypto-encrypt-hex/
func Crypto_encrypt_hex(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Crypto_encrypt_hex_Validate(args); err != nil {
		return value.Null, err
	}

	// Need to be implemented
	return value.Null, errors.NotImplemented("crypto.encrypt_hex")
}
