// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"testing"
	// "github.com/ysugimoto/falco/interpreter/context"
	// "github.com/ysugimoto/falco/interpreter/value"
)

// Fastly built-in function testing implementation of cstr_escape
// Arguments may be:
// - STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/strings/cstr-escape/
func Test_Cstr_escape(t *testing.T) {
	t.Skip("Test Builtin function cstr_escape should be impelemented")
}
