// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"crypto/hmac"
	"crypto/sha512"
	"encoding/hex"

	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Digest_hmac_sha512_Name = "digest.hmac_sha512"

var Digest_hmac_sha512_ArgumentTypes = []value.Type{value.StringType, value.StringType}

func Digest_hmac_sha512_Validate(args []value.Value) error {
	if len(args) != 2 {
		return errors.ArgumentNotEnough(Digest_hmac_sha512_Name, 2, args)
	}
	for i := range args {
		if args[i].Type() != Digest_hmac_sha512_ArgumentTypes[i] {
			return errors.TypeMismatch(Digest_hmac_sha512_Name, i+1, Digest_hmac_sha512_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of digest.hmac_sha512
// Arguments may be:
// - STRING, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/cryptographic/digest-hmac-sha512/
func Digest_hmac_sha512(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Digest_hmac_sha512_Validate(args); err != nil {
		return value.Null, err
	}

	key := value.GetString(args[0]).String()
	input := value.GetString(args[1]).String()
	mac := hmac.New(sha512.New, []byte(key))
	mac.Write([]byte(input))

	return &value.String{
		Value: hex.EncodeToString(mac.Sum(nil)),
	}, nil
}
