// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Digest_awsv4_hmac_Name = "digest.awsv4_hmac"

var Digest_awsv4_hmac_ArgumentTypes = []value.Type{value.StringType, value.StringType, value.StringType, value.StringType, value.StringType}

func Digest_awsv4_hmac_Validate(args []value.Value) error {
	if len(args) != 5 {
		return errors.ArgumentNotEnough(Digest_awsv4_hmac_Name, 5, args)
	}
	for i := range args {
		if args[i].Type() != Digest_awsv4_hmac_ArgumentTypes[i] {
			return errors.TypeMismatch(Digest_awsv4_hmac_Name, i+1, Digest_awsv4_hmac_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of digest.awsv4_hmac
// Arguments may be:
// - STRING, STRING, STRING, STRING, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/cryptographic/digest-awsv4-hmac/
func Digest_awsv4_hmac(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Digest_awsv4_hmac_Validate(args); err != nil {
		return value.Null, err
	}

	// Need to be implemented
	return value.Null, errors.NotImplemented("digest.awsv4_hmac")
}
