// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"testing"
	// "github.com/ysugimoto/falco/interpreter/context"
	// "github.com/ysugimoto/falco/interpreter/value"
)

// Fastly built-in function testing implementation of digest.secure_is_equal
// Arguments may be:
// - STRING, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/cryptographic/digest-secure-is-equal/
func Test_Digest_secure_is_equal(t *testing.T) {
	t.Skip("Test Builtin function digest.secure_is_equal should be impelemented")
}
