// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"testing"

	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/value"
)

// Fastly built-in function testing implementation of digest.awsv4_hmac
// Arguments may be:
// - STRING, STRING, STRING, STRING, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/cryptographic/digest-awsv4-hmac/
func Test_Digest_awsv4_hmac(t *testing.T) {

	// example from https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html
	ret, err := Digest_awsv4_hmac(
		&context.Context{},
		&value.String{Value: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"},
		&value.String{Value: "20130524"},
		&value.String{Value: "us-east-1"},
		&value.String{Value: "s3"},
		&value.String{Value: "AWS4-HMAC-SHA256\n20130524T000000Z\n20130524/us-east-1/s3/aws4_request\n7344ae5b7ee6c3e7e6b0fe0640412a37625d1fbfff95c48bbb2dc43964946972"},
	)
	if err != nil {
		t.Errorf("Unexpected error: %s", err)
	}
	if ret.Type() != value.StringType {
		t.Errorf("Unexpected return type, expect=STRING, got=%s", ret.Type())
	}
	v := value.Unwrap[*value.String](ret)
	expect := "f0e8bdb87c964420e857bd35b5d6ed310bd44f0170aba48dd91039c6036bdb41"
	if v.Value != expect {
		t.Errorf("Return value unmatch, expect=%s, got=%s", expect, v.Value)
	}
}
