// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Digest_secure_is_equal_Name = "digest.secure_is_equal"

var Digest_secure_is_equal_ArgumentTypes = []value.Type{value.StringType, value.StringType}

func Digest_secure_is_equal_Validate(args []value.Value) error {
	if len(args) != 2 {
		return errors.ArgumentNotEnough(Digest_secure_is_equal_Name, 2, args)
	}
	for i := range args {
		if args[i].Type() != Digest_secure_is_equal_ArgumentTypes[i] {
			return errors.TypeMismatch(Digest_secure_is_equal_Name, i+1, Digest_secure_is_equal_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of digest.secure_is_equal
// Arguments may be:
// - STRING, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/cryptographic/digest-secure-is-equal/
func Digest_secure_is_equal(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Digest_secure_is_equal_Validate(args); err != nil {
		return value.Null, err
	}

	// Need to be implemented
	return value.Null, errors.NotImplemented("digest.secure_is_equal")
}
