// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"testing"
	// "github.com/ysugimoto/falco/interpreter/context"
	// "github.com/ysugimoto/falco/interpreter/value"
)

// Fastly built-in function testing implementation of digest.time_hmac_md5
// Arguments may be:
// - STRING, INTEGER, INTEGER
// Reference: https://developer.fastly.com/reference/vcl/functions/cryptographic/digest-time-hmac-md5/
func Test_Digest_time_hmac_md5(t *testing.T) {
	t.Skip("Test Builtin function digest.time_hmac_md5 should be impelemented")
}
