// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"testing"
	// "github.com/ysugimoto/falco/interpreter/context"
	// "github.com/ysugimoto/falco/interpreter/value"
)

// Fastly built-in function testing implementation of digest.ecdsa_verify
// Arguments may be:
// - ID, STRING, STRING, STRING, ID
// - ID, STRING, STRING, STRING, ID, ID
// Reference: https://www.fastly.com/documentation/reference/vcl/functions/cryptographic/digest-ecdsa-verify/
func Test_Digest_ecdsa_verify(t *testing.T) {
	t.Skip("Test Builtin function digest.ecdsa_verify should be impelemented")
}
