// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"testing"
)

// Fastly built-in function testing implementation of fastly.try_select_shield
// Arguments may be:
// - BACKEND, BACKEND
// Reference: https://www.fastly.com/documentation/reference/vcl/functions/miscellaneous/fastly-try-select-shield/
func Test_Fastly_try_select_shield(t *testing.T) {
	t.Skip("Test Builtin function fastly.try_select_shield should be impelemented")
}
