// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

const H2_disable_header_compression_Name = "h2.disable_header_compression"

func H2_disable_header_compression_Validate(args []value.Value) error {
	// Note: this function accepts variadic arguments
	if len(args) == 0 {
		return errors.New(H2_disable_header_compression_Name, "At least 1 arguments")
	}
	for i := range args {
		if args[i].Type() != value.StringType {
			return errors.TypeMismatch(H2_disable_header_compression_Name, i+1, value.StringType, args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of h2.disable_header_compression
// Arguments may be:
// - STRING_LIST
// Reference: https://developer.fastly.com/reference/vcl/functions/tls-and-http/h2-disable-header-compression/
func H2_disable_header_compression(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := H2_disable_header_compression_Validate(args); err != nil {
		return value.Null, err
	}

	for i := range args {
		v := value.Unwrap[*value.String](args[i])
		ctx.DisableCompressionHeaders = append(ctx.DisableCompressionHeaders, v.Value)
	}

	// nil means VOID type
	return nil, nil
}
