// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"net"
	"net/http"
	"testing"
	"time"

	"github.com/google/go-cmp/cmp"
	"github.com/k0kubun/pp"
	"github.com/ysugimoto/falco/ast"
	"github.com/ysugimoto/falco/interpreter/context"
	flchttp "github.com/ysugimoto/falco/interpreter/http"
	"github.com/ysugimoto/falco/interpreter/value"
)

// Fastly built-in function testing implementation of header.get
// Arguments may be:
// - ID, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/headers/header-get/
func Test_Header_get(t *testing.T) {

	t.Run("Invalid arguments", func(t *testing.T) {
		tests := []struct {
			name value.Value
		}{
			{name: &value.String{Value: ""}},
			{name: &value.String{Value: "Invalid%Header$<>"}},
		}
		for i, tt := range tests {
			req, _ := flchttp.NewRequest(http.MethodGet, "http://localhost:3124", nil)
			req.Header.Set("X-Custom-Header", &value.String{Value: "value"})
			req.Header.Set("Object:foo", &value.String{Value: "valuefoo"})
			req.Header.Set("Object:bar", &value.String{Value: "valuebar"})
			ctx := &context.Context{Request: req}

			v, err := Header_get(ctx, &value.Ident{Value: "req"}, tt.name)
			if err != nil {
				t.Errorf("[%d] Header_get should not return error but non-nil: %s", i, err)
				continue
			}

			if diff := cmp.Diff(v, &value.LenientString{IsNotSet: true}); diff != "" {
				t.Errorf("[%d] Unexpected value returned, diff=%s", i, diff)
			}
		}
	})

	t.Run("get from req", func(t *testing.T) {
		now := time.Now()
		tests := []struct {
			name     value.Value
			expect   string
			isNotSet bool
			isError  bool
		}{
			{name: &value.String{Value: "X-Custom-Header"}, expect: "value"},
			{name: &value.String{Value: "X-Not-Found"}, isNotSet: true},
			{name: &value.String{Value: "Object:foo"}, expect: "valuefoo"},
			{name: &value.Integer{Value: 10}, isNotSet: true},
			{name: &value.Integer{Value: 10, Literal: true}, isError: true},
			{name: &value.Float{Value: 10}, isNotSet: true},
			{name: &value.Float{Value: 10, Literal: true}, isError: true},
			{name: &value.Boolean{Value: false}, isNotSet: true},
			{name: &value.Boolean{Value: true, Literal: true}, expect: "1"},
			{name: &value.RTime{Value: time.Second}, isNotSet: true},
			{name: &value.RTime{Value: time.Second, Literal: true}, isError: true},
			{name: &value.Time{Value: now}, isNotSet: true},
			{name: &value.IP{Value: net.ParseIP("192.168.0.1")}, isNotSet: true},
			{name: &value.Backend{
				Value: &ast.BackendDeclaration{
					Name: &ast.Ident{Value: "example"},
				},
			}, isNotSet: true},
			{name: &value.Backend{
				Literal: true,
				Value: &ast.BackendDeclaration{
					Name: &ast.Ident{Value: "example"},
				},
			}, isError: true},
			{name: &value.Acl{
				Value: &ast.AclDeclaration{
					Name: &ast.Ident{Value: "example"},
				},
			}, isError: true},
		}

		for i, tt := range tests {
			req, _ := flchttp.NewRequest(http.MethodGet, "http://localhost:3124", nil)
			req.Header.Set("X-Custom-Header", &value.String{Value: "value"})
			req.Header.Set("Object:foo", &value.String{Value: "valuefoo"})
			req.Header.Set("Object:bar", &value.String{Value: "valuebar"})
			ctx := &context.Context{Request: req}

			v, err := Header_get(ctx, &value.Ident{Value: "req"}, tt.name)
			if tt.isError {
				if err == nil {
					t.Errorf("[%d] Header_get should return error but non-nil", i)
				}
				continue
			} else {
				if err != nil {
					t.Errorf("[%d] Header_get should not return error but non-nil: %s", i, err)
					continue
				}
			}

			if tt.isNotSet {
				if diff := cmp.Diff(v, &value.LenientString{IsNotSet: true}); diff != "" {
					t.Errorf("[%d] Unexpected value returned, diff=%s", i, diff)
				}
				return
			}

			str := value.GetString(v).String()
			if diff := cmp.Diff(str, tt.expect); diff != "" {
				t.Errorf("[%d] Unexpected value returned, diff=%s", i, diff)
			}
		}
	})

	t.Run("get from bereq", func(t *testing.T) {
		now := time.Now()
		tests := []struct {
			name     value.Value
			expect   string
			isNotSet bool
			isError  bool
		}{
			{name: &value.String{Value: "X-Custom-Header"}, expect: "value"},
			{name: &value.String{Value: "X-Not-Found"}, isNotSet: true},
			{name: &value.String{Value: "Object:foo"}, expect: "valuefoo"},
			{name: &value.Integer{Value: 10}, isNotSet: true},
			{name: &value.Integer{Value: 10, Literal: true}, isError: true},
			{name: &value.Float{Value: 10}, isNotSet: true},
			{name: &value.Float{Value: 10, Literal: true}, isError: true},
			{name: &value.Boolean{Value: false}, isNotSet: true},
			{name: &value.Boolean{Value: true, Literal: true}, expect: "1"},
			{name: &value.RTime{Value: time.Second}, isNotSet: true},
			{name: &value.RTime{Value: time.Second, Literal: true}, isError: true},
			{name: &value.Time{Value: now}, isNotSet: true},
			{name: &value.IP{Value: net.ParseIP("192.168.0.1")}, isNotSet: true},
			{name: &value.Backend{
				Value: &ast.BackendDeclaration{
					Name: &ast.Ident{Value: "example"},
				},
			}, isNotSet: true},
			{name: &value.Backend{
				Literal: true,
				Value: &ast.BackendDeclaration{
					Name: &ast.Ident{Value: "example"},
				},
			}, isError: true},
			{name: &value.Acl{
				Value: &ast.AclDeclaration{
					Name: &ast.Ident{Value: "example"},
				},
			}, isError: true},
		}

		for i, tt := range tests {
			req, _ := flchttp.NewRequest(http.MethodGet, "http://localhost:3124", nil)
			req.Header.Set("X-Custom-Header", &value.String{Value: "value"})
			req.Header.Set("Object:foo", &value.String{Value: "valuefoo"})
			req.Header.Set("Object:bar", &value.String{Value: "valuebar"})
			ctx := &context.Context{BackendRequest: req}

			v, err := Header_get(ctx, &value.Ident{Value: "bereq"}, tt.name)
			if tt.isError {
				if err == nil {
					t.Errorf("[%d] Header_get should return error but non-nil", i)
				}
				continue
			} else {
				if err != nil {
					t.Errorf("[%d] Header_get should not return error but non-nil: %s", i, err)
					continue
				}
			}

			if tt.isNotSet {
				if diff := cmp.Diff(v, &value.LenientString{IsNotSet: true}); diff != "" {
					t.Errorf("[%d] Unexpected value returned, diff=%s", i, diff)
				}
				return
			}

			str := value.GetString(v).String()
			if diff := cmp.Diff(str, tt.expect); diff != "" {
				t.Errorf("[%d] Unexpected value returned, diff=%s", i, diff)
			}
		}
	})

	t.Run("get from beresp", func(t *testing.T) {
		now := time.Now()
		tests := []struct {
			name     value.Value
			expect   string
			isNotSet bool
			isError  bool
		}{
			{name: &value.String{Value: "X-Custom-Header"}, expect: "value"},
			{name: &value.String{Value: "X-Not-Found"}, isNotSet: true},
			{name: &value.String{Value: "Object:foo"}, expect: "valuefoo"},
			{name: &value.Integer{Value: 10}, isNotSet: true},
			{name: &value.Integer{Value: 10, Literal: true}, isError: true},
			{name: &value.Float{Value: 10}, isNotSet: true},
			{name: &value.Float{Value: 10, Literal: true}, isError: true},
			{name: &value.Boolean{Value: false}, isNotSet: true},
			{name: &value.Boolean{Value: true, Literal: true}, expect: "1"},
			{name: &value.RTime{Value: time.Second}, isNotSet: true},
			{name: &value.RTime{Value: time.Second, Literal: true}, isError: true},
			{name: &value.Time{Value: now}, isNotSet: true},
			{name: &value.IP{Value: net.ParseIP("192.168.0.1")}, isNotSet: true},
			{name: &value.Backend{
				Value: &ast.BackendDeclaration{
					Name: &ast.Ident{Value: "example"},
				},
			}, isNotSet: true},
			{name: &value.Backend{
				Literal: true,
				Value: &ast.BackendDeclaration{
					Name: &ast.Ident{Value: "example"},
				},
			}, isError: true},
			{name: &value.Acl{
				Value: &ast.AclDeclaration{
					Name: &ast.Ident{Value: "example"},
				},
			}, isError: true},
		}

		for i, tt := range tests {
			resp := &flchttp.Response{
				Header: flchttp.Header{},
			}
			resp.Header.Set("X-Custom-Header", &value.String{Value: "value"})
			resp.Header.Set("Object:foo", &value.String{Value: "valuefoo"})
			resp.Header.Set("Object:bar", &value.String{Value: "valuebar"})
			ctx := &context.Context{BackendResponse: resp}

			v, err := Header_get(ctx, &value.Ident{Value: "beresp"}, tt.name)
			if tt.isError {
				if err == nil {
					t.Errorf("[%d] Header_get should return error but non-nil", i)
				}
				continue
			} else {
				if err != nil {
					t.Errorf("[%d] Header_get should not return error but non-nil: %s", i, err)
					continue
				}
			}

			if tt.isNotSet {
				if diff := cmp.Diff(v, &value.LenientString{IsNotSet: true}); diff != "" {
					t.Errorf("[%d] Unexpected value returned, diff=%s", i, diff)
				}
				return
			}

			str := value.GetString(v).String()
			if diff := cmp.Diff(str, tt.expect); diff != "" {
				t.Errorf("[%d] Unexpected value returned, diff=%s", i, diff)
			}
		}
	})

	t.Run("get from obj", func(t *testing.T) {
		now := time.Now()
		tests := []struct {
			name     value.Value
			expect   string
			isNotSet bool
			isError  bool
		}{
			{name: &value.String{Value: "X-Custom-Header"}, expect: "value"},
			{name: &value.String{Value: "X-Not-Found"}, isNotSet: true},
			{name: &value.String{Value: "Object:foo"}, expect: "valuefoo"},
			{name: &value.Integer{Value: 10}, isNotSet: true},
			{name: &value.Integer{Value: 10, Literal: true}, isError: true},
			{name: &value.Float{Value: 10}, isNotSet: true},
			{name: &value.Float{Value: 10, Literal: true}, isError: true},
			{name: &value.Boolean{Value: false}, isNotSet: true},
			{name: &value.Boolean{Value: true, Literal: true}, expect: "1"},
			{name: &value.RTime{Value: time.Second}, isNotSet: true},
			{name: &value.RTime{Value: time.Second, Literal: true}, isError: true},
			{name: &value.Time{Value: now}, isNotSet: true},
			{name: &value.IP{Value: net.ParseIP("192.168.0.1")}, isNotSet: true},
			{name: &value.Backend{
				Value: &ast.BackendDeclaration{
					Name: &ast.Ident{Value: "example"},
				},
			}, isNotSet: true},
			{name: &value.Backend{
				Literal: true,
				Value: &ast.BackendDeclaration{
					Name: &ast.Ident{Value: "example"},
				},
			}, isError: true},
			{name: &value.Acl{
				Value: &ast.AclDeclaration{
					Name: &ast.Ident{Value: "example"},
				},
			}, isError: true},
		}

		for i, tt := range tests {
			resp := &flchttp.Response{
				Header: flchttp.Header{},
			}
			resp.Header.Set("X-Custom-Header", &value.String{Value: "value"})
			resp.Header.Set("Object:foo", &value.String{Value: "valuefoo"})
			resp.Header.Set("Object:bar", &value.String{Value: "valuebar"})
			ctx := &context.Context{Object: resp}

			v, err := Header_get(
				ctx,
				&value.Ident{Value: "obj"},
				tt.name,
			)
			if tt.isError {
				if err == nil {
					t.Errorf("[%d] Header_get should return error but non-nil", i)
				}
				continue
			} else {
				if err != nil {
					t.Errorf("[%d] Header_get should not return error but non-nil: %s", i, err)
					continue
				}
			}

			if tt.isNotSet {
				if diff := cmp.Diff(v, &value.LenientString{IsNotSet: true}); diff != "" {
					t.Errorf("[%d] Unexpected value returned, diff=%s", i, diff)
				}
				return
			}

			str := value.GetString(v).String()
			if diff := cmp.Diff(str, tt.expect); diff != "" {
				t.Errorf("[%d] Unexpected value returned, diff=%s", i, diff)
			}
		}
	})

	t.Run("get from response", func(t *testing.T) {
		now := time.Now()
		tests := []struct {
			name     value.Value
			expect   string
			isNotSet bool
			isError  bool
		}{
			{name: &value.String{Value: "X-Custom-Header"}, expect: "value"},
			{name: &value.String{Value: "X-Not-Found"}, isNotSet: true},
			{name: &value.String{Value: "Object:foo"}, expect: "valuefoo"},
			{name: &value.Integer{Value: 10}, isNotSet: true},
			{name: &value.Integer{Value: 10, Literal: true}, isError: true},
			{name: &value.Float{Value: 10}, isNotSet: true},
			{name: &value.Float{Value: 10, Literal: true}, isError: true},
			{name: &value.Boolean{Value: false}, isNotSet: true},
			{name: &value.Boolean{Value: true, Literal: true}, expect: "1"},
			{name: &value.RTime{Value: time.Second}, isNotSet: true},
			{name: &value.RTime{Value: time.Second, Literal: true}, isError: true},
			{name: &value.Time{Value: now}, isNotSet: true},
			{name: &value.IP{Value: net.ParseIP("192.168.0.1")}, isNotSet: true},
			{name: &value.Backend{
				Value: &ast.BackendDeclaration{
					Name: &ast.Ident{Value: "example"},
				},
			}, isNotSet: true},
			{name: &value.Backend{
				Literal: true,
				Value: &ast.BackendDeclaration{
					Name: &ast.Ident{Value: "example"},
				},
			}, isError: true},
			{name: &value.Acl{
				Value: &ast.AclDeclaration{
					Name: &ast.Ident{Value: "example"},
				},
			}, isError: true},
		}

		for i, tt := range tests {
			resp := &flchttp.Response{
				Header: flchttp.Header{},
			}
			resp.Header.Set("X-Custom-Header", &value.String{Value: "value"})
			resp.Header.Set("Object:foo", &value.String{Value: "valuefoo"})
			resp.Header.Set("Object:bar", &value.String{Value: "valuebar"})
			ctx := &context.Context{Response: resp}

			v, err := Header_get(
				ctx,
				&value.Ident{Value: "resp"},
				tt.name,
			)
			if tt.isError {
				if err == nil {
					t.Errorf("[%d] Header_get should return error but non-nil", i)
				}
				continue
			} else {
				if err != nil {
					t.Errorf("[%d] Header_get should not return error but non-nil: %s", i, err)
					continue
				}
			}

			if tt.isNotSet {
				if diff := cmp.Diff(v, &value.LenientString{IsNotSet: true}); diff != "" {
					t.Errorf("[%d] Unexpected value returned, diff=%s", i, diff)
				}
				return
			}

			str := value.GetString(v).String()
			if diff := cmp.Diff(str, tt.expect); diff != "" {
				t.Errorf("[%d] Unexpected value returned, diff=%s", i, diff)
			}

		}
	})

	t.Run("get from invalid id", func(t *testing.T) {
		now := time.Now()
		tests := []struct {
			name     value.Value
			expect   string
			isNotSet bool
		}{
			{name: &value.String{Value: "X-Custome-Header"}, expect: "value"},
			{name: &value.String{Value: "X-Not-Found"}, isNotSet: true},
			{name: &value.String{Value: "Object:foo"}, expect: "valuefoo"},
			{name: &value.Integer{Value: 10}, isNotSet: true},
			{name: &value.Integer{Value: 10, Literal: true}},
			{name: &value.Float{Value: 10}, isNotSet: true},
			{name: &value.Float{Value: 10, Literal: true}},
			{name: &value.Boolean{Value: false}, isNotSet: true},
			{name: &value.Boolean{Value: true, Literal: true}, isNotSet: true},
			{name: &value.RTime{Value: time.Second}, isNotSet: true},
			{name: &value.RTime{Value: time.Second, Literal: true}},
			{name: &value.Time{Value: now}},
			{name: &value.IP{Value: net.ParseIP("192.168.0.1")}, isNotSet: true},
			{name: &value.Backend{
				Value: &ast.BackendDeclaration{
					Name: &ast.Ident{Value: "example"},
				},
			}},
			{name: &value.Backend{
				Literal: true,
				Value: &ast.BackendDeclaration{
					Name: &ast.Ident{Value: "example"},
				},
			}},
			{name: &value.Acl{
				Value: &ast.AclDeclaration{
					Name: &ast.Ident{Value: "example"},
				},
			}},
		}

		for i, tt := range tests {
			resp := &flchttp.Response{
				Header: flchttp.Header{},
			}
			resp.Header.Set("X-Custom-Header", &value.String{Value: "value"})
			resp.Header.Set("Object:foo", &value.String{Value: "valuefoo"})
			resp.Header.Set("Object:bar", &value.String{Value: "valuebar"})
			ctx := &context.Context{Response: resp}

			v, err := Header_get(ctx, &value.Ident{Value: "foo"}, tt.name)
			if err == nil {
				pp.Println(tt, v)
				t.Errorf("[%d] Header_get expects error but nil", i)
			}
		}
	})
}
