// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Header_unset_Name = "header.unset"

var Header_unset_ArgumentTypes = []value.Type{value.IdentType, value.StringType}

func Header_unset_Validate(args []value.Value) error {
	if len(args) != 2 {
		return errors.ArgumentNotEnough(Header_unset_Name, 2, args)
	}
	for i := range args {
		if args[i].Type() != Header_unset_ArgumentTypes[i] {
			return errors.TypeMismatch(Header_unset_Name, i+1, Header_unset_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of header.unset
// Arguments may be:
// - ID, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/headers/header-unset/
func Header_unset(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Header_unset_Validate(args); err != nil {
		return value.Null, err
	}

	// Need to be implemented
	return value.Null, errors.NotImplemented("header.unset")
}
