// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

var Http_status_matches_ArgumentTypes = []value.Type{value.IntegerType, value.StringType}

func Http_status_matches_Validate(args []value.Value) error {
	if len(args) != 2 {
		return errors.ArgumentNotEnough("http_status_matches", 2, args)
	}
	for i := range args {
		if args[i].Type() != Http_status_matches_ArgumentTypes[i] {
			return errors.TypeMismatch("http_status_matches", i+1, Http_status_matches_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of http_status_matches
// Arguments may be:
// - INTEGER, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/miscellaneous/http-status-matches/
func Http_status_matches(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Http_status_matches_Validate(args); err != nil {
		return value.Null, err
	}

	// Need to be implemented
	return value.Null, errors.NotImplemented("http_status_matches")
}
