// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Json_escape_Name = "json.escape"

var Json_escape_ArgumentTypes = []value.Type{value.StringType}

func Json_escape_Validate(args []value.Value) error {
	if len(args) != 1 {
		return errors.ArgumentNotEnough(Json_escape_Name, 1, args)
	}
	for i := range args {
		if args[i].Type() != Json_escape_ArgumentTypes[i] {
			return errors.TypeMismatch(Json_escape_Name, i+1, Json_escape_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of json.escape
// Arguments may be:
// - STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/strings/json-escape/
func Json_escape(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Json_escape_Validate(args); err != nil {
		return value.Null, err
	}

	// Need to be implemented
	return value.Null, errors.NotImplemented("json.escape")
}
