// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Math_log2_Name = "math.log2"

var Math_log2_ArgumentTypes = []value.Type{value.FloatType}

func Math_log2_Validate(args []value.Value) error {
	if len(args) != 1 {
		return errors.ArgumentNotEnough(Math_log2_Name, 1, args)
	}
	for i := range args {
		if args[i].Type() != Math_log2_ArgumentTypes[i] {
			return errors.TypeMismatch(Math_log2_Name, i+1, Math_log2_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of math.log2
// Arguments may be:
// - FLOAT
// Reference: https://developer.fastly.com/reference/vcl/functions/math-logexp/math-log2/
func Math_log2(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Math_log2_Validate(args); err != nil {
		return value.Null, err
	}

	// Need to be implemented
	return value.Null, errors.NotImplemented("math.log2")
}
