// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Math_atan_Name = "math.atan"

var Math_atan_ArgumentTypes = []value.Type{value.FloatType}

func Math_atan_Validate(args []value.Value) error {
	if len(args) != 1 {
		return errors.ArgumentNotEnough(Math_atan_Name, 1, args)
	}
	for i := range args {
		if args[i].Type() != Math_atan_ArgumentTypes[i] {
			return errors.TypeMismatch(Math_atan_Name, i+1, Math_atan_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of math.atan
// Arguments may be:
// - FLOAT
// Reference: https://developer.fastly.com/reference/vcl/functions/math-trig/math-atan/
func Math_atan(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Math_atan_Validate(args); err != nil {
		return value.Null, err
	}

	// Need to be implemented
	return value.Null, errors.NotImplemented("math.atan")
}
