// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/function/shared"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Querystring_clean_Name = "querystring.clean"

var Querystring_clean_ArgumentTypes = []value.Type{value.StringType}

func Querystring_clean_Validate(args []value.Value) error {
	if len(args) != 1 {
		return errors.ArgumentNotEnough(Querystring_clean_Name, 1, args)
	}
	for i := range args {
		if args[i].Type() != Querystring_clean_ArgumentTypes[i] {
			return errors.TypeMismatch(Querystring_clean_Name, i+1, Querystring_clean_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of querystring.clean
// Arguments may be:
// - STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/query-string/querystring-clean/
func Querystring_clean(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Querystring_clean_Validate(args); err != nil {
		return value.Null, err
	}

	v := value.Unwrap[*value.String](args[0])
	result := shared.QueryStringClean(v.Value)
	return &value.String{Value: result}, nil
}
