// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

var Querystring_regfilter_except_ArgumentTypes = []value.Type{value.StringType, value.StringType}

func Querystring_regfilter_except_Validate(args []value.Value) error {
	if len(args) != 2 {
		return errors.ArgumentNotEnough("querystring.regfilter_except", 2, args)
	}
	for i := range args {
		if args[i].Type() != Querystring_regfilter_except_ArgumentTypes[i] {
			return errors.TypeMismatch("querystring.regfilter_except", i+1, Querystring_regfilter_except_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of querystring.regfilter_except
// Arguments may be:
// - STRING, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/query-string/querystring-regfilter-except/
func Querystring_regfilter_except(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Querystring_regfilter_except_Validate(args); err != nil {
		return value.Null, err
	}

	// Need to be implemented
	return value.Null, errors.NotImplemented("querystring.regfilter_except")
}
