// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Ratelimit_penaltybox_has_Name = "ratelimit.penaltybox_has"

var Ratelimit_penaltybox_has_ArgumentTypes = []value.Type{value.IdentType, value.StringType}

func Ratelimit_penaltybox_has_Validate(args []value.Value) error {
	if len(args) != 2 {
		return errors.ArgumentNotEnough(Ratelimit_penaltybox_has_Name, 2, args)
	}
	for i := range args {
		if i == 1 { // second argument could accept string or IP type
			if args[i].Type() != value.StringType && args[i].Type() != value.IpType {
				return errors.TypeMismatch(Ratelimit_penaltybox_has_Name, i+1, Ratelimit_penaltybox_has_ArgumentTypes[i], args[i].Type())
			}
			continue
		}
		if args[i].Type() != Ratelimit_penaltybox_has_ArgumentTypes[i] {
			return errors.TypeMismatch(Ratelimit_penaltybox_has_Name, i+1, Ratelimit_penaltybox_has_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of ratelimit.penaltybox_has
// Arguments may be:
// - ID, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/rate-limiting/ratelimit-penaltybox-has/
func Ratelimit_penaltybox_has(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Ratelimit_penaltybox_has_Validate(args); err != nil {
		return value.Null, err
	}

	name := value.Unwrap[*value.Ident](args[0]).Value
	var entry string
	switch args[1].Type() {
	case value.StringType:
		entry = value.Unwrap[*value.String](args[1]).Value
	case value.IpType:
		entry = value.Unwrap[*value.IP](args[1]).String()
	}

	pb, ok := ctx.Penaltyboxes[name]
	if !ok {
		return value.Null, errors.New(Ratelimit_penaltybox_add_Name, "Penaltybox %s is not defined", name)
	}
	return &value.Boolean{
		Value: pb.Has(entry),
	}, nil
}
