// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"testing"
	"time"

	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/value"
)

func Test_Ratelimit_check_rate(t *testing.T) {
	tests := []struct {
		name         string
		args         []value.Value
		wantExceeded bool
		wantErr      bool
	}{
		{
			name: "exceeded",
			args: []value.Value{
				&value.String{Value: "192.0.2.1"},
				&value.Ident{Value: "rc1"},
				&value.Integer{Value: 101},
				&value.Integer{Value: 1},
				&value.Integer{Value: 100},
				&value.Ident{Value: "pb"},
				&value.RTime{Value: 10 * time.Second},
			},
			wantExceeded: true,
		},
		{
			name: "not exceeded",
			args: []value.Value{
				&value.String{Value: "192.0.2.2"},
				&value.Ident{Value: "rc1"},
				&value.Integer{Value: 10},
				&value.Integer{Value: 1},
				&value.Integer{Value: 100},
				&value.Ident{Value: "pb"},
				&value.RTime{Value: 10 * time.Second},
			},
			wantExceeded: false,
		},
	}

	// Wait for next window
	for time.Now().Unix()%10 != 0 {
		time.Sleep(time.Second)
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			rc1 := value.NewRatecounter(nil)
			pb := value.NewPenaltybox(nil)
			ctx := &context.Context{
				Ratecounters: map[string]*value.Ratecounter{
					"rc1": rc1,
				},
				Penaltyboxes: map[string]*value.Penaltybox{
					"pb": pb,
				},
			}

			ret, err := Ratelimit_check_rate(ctx, tt.args...)
			if tt.wantErr {
				if err == nil {
					t.Errorf("Expected error but got nil")
				}
				return
			}
			if err != nil {
				t.Errorf("Unexpected error: %s", err)
				return
			}
			b := value.Unwrap[*value.Boolean](ret)
			if b.Value != tt.wantExceeded {
				t.Errorf("Unexpected return value, expect=%t, got=%t", tt.wantExceeded, b.Value)
			}
		})
	}
}
