// Code generated by __generator__/interpreter.go; DO NOT EDIT.

package builtin

import (
	"fmt"

	"github.com/pkg/errors"
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/value"
)

// Fastly built-in function implementation of ratelimit.ratecounter_increment
// Arguments may be:
// - ID, STRING, INTEGER
// Reference: https://developer.fastly.com/reference/vcl/functions/rate-limiting/ratelimit-ratecounter-increment/
func Ratelimit_ratecounter_increment(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Need to be implemented
	return value.Null, errors.WithStack(fmt.Errorf("Builtin function ratelimit.ratecounter_increment is not impelemented"))
}
