// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"strings"

	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Std_strcasecmp_Name = "std.strcasecmp"

var Std_strcasecmp_ArgumentTypes = []value.Type{value.StringType, value.StringType}

func Std_strcasecmp_Validate(args []value.Value) error {
	if len(args) != 2 {
		return errors.ArgumentNotEnough(Std_strcasecmp_Name, 2, args)
	}
	for i := range args {
		if args[i].Type() != Std_strcasecmp_ArgumentTypes[i] {
			return errors.TypeMismatch(Std_strcasecmp_Name, i+1, Std_strcasecmp_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of std.strcasecmp
// Arguments may be:
// - STRING, STRING
// Reference:
func Std_strcasecmp(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Std_strcasecmp_Validate(args); err != nil {
		return value.Null, err
	}

	haystack := value.Unwrap[*value.String](args[0]).Value
	needle := value.Unwrap[*value.String](args[1]).Value

	return &value.Boolean{
		Value: strings.EqualFold(haystack, needle),
	}, nil
}
