// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

var Std_strtof_ArgumentTypes = []value.Type{value.StringType, value.IntegerType}

func Std_strtof_Validate(args []value.Value) error {
	if len(args) != 2 {
		return errors.ArgumentNotEnough("std.strtof", 2, args)
	}
	for i := range args {
		if args[i].Type() != Std_strtof_ArgumentTypes[i] {
			return errors.TypeMismatch("std.strtof", i+1, Std_strtof_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of std.strtof
// Arguments may be:
// - STRING, INTEGER
// Reference: https://developer.fastly.com/reference/vcl/functions/strings/std-strtof/
func Std_strtof(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Std_strtof_Validate(args); err != nil {
		return value.Null, err
	}

	// Need to be implemented
	return value.Null, errors.NotImplemented("std.strtof")
}
