// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Std_tolower_Name = "std.tolower"

var Std_tolower_ArgumentTypes = []value.Type{value.StringType}

func Std_tolower_Validate(args []value.Value) error {
	if len(args) != 1 {
		return errors.ArgumentNotEnough(Std_tolower_Name, 1, args)
	}
	for i := range args {
		if args[i].Type() != Std_tolower_ArgumentTypes[i] {
			return errors.TypeMismatch(Std_tolower_Name, i+1, Std_tolower_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of std.tolower
// Arguments may be:
// - STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/strings/std-tolower/
func Std_tolower(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Std_tolower_Validate(args); err != nil {
		return value.Null, err
	}

	// Need to be implemented
	return value.Null, errors.NotImplemented("std.tolower")
}
