// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"testing"
	// "github.com/ysugimoto/falco/interpreter/context"
	// "github.com/ysugimoto/falco/interpreter/value"
)

// Fastly built-in function testing implementation of std.count
// Arguments may be:
// - ID
// Reference: https://developer.fastly.com/reference/vcl/functions/miscellaneous/std-count/
func Test_Std_count(t *testing.T) {
	t.Skip("Test Builtin function std.count should be impelemented")
}
