// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"testing"
	// "github.com/ysugimoto/falco/interpreter/context"
	// "github.com/ysugimoto/falco/interpreter/value"
)

// Fastly built-in function testing implementation of std.dirname
// Arguments may be:
// - STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/strings/std-dirname/
func Test_Std_dirname(t *testing.T) {
	t.Skip("Test Builtin function std.dirname should be impelemented")
}
