// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"math"
	"strings"

	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Std_strpad_Name = "std.strpad"

var Std_strpad_ArgumentTypes = []value.Type{value.StringType, value.IntegerType, value.StringType}

func Std_strpad_Validate(args []value.Value) error {
	if len(args) != 3 {
		return errors.ArgumentNotEnough(Std_strpad_Name, 3, args)
	}
	for i := range args {
		if args[i].Type() != Std_strpad_ArgumentTypes[i] {
			return errors.TypeMismatch(Std_strpad_Name, i+1, Std_strpad_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of std.strpad
// Arguments may be:
// - STRING, INTEGER, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/strings/std-strpad/
func Std_strpad(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Std_strpad_Validate(args); err != nil {
		return value.Null, err
	}

	s := value.GetString(args[0]).String()
	width := value.Unwrap[*value.Integer](args[1]).Value
	pad := value.GetString(args[2]).String()

	w := int(math.Abs(float64(width)))
	if len(s) >= w {
		return &value.String{Value: s}, nil
	}

	p := strings.Repeat(pad, w-len(s))
	if width < 0 {
		return &value.String{Value: s + p[0:w-len(s)]}, nil
	}
	return &value.String{Value: p[0:w-len(s)] + s}, nil
}
