// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"strings"

	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Std_replace_Name = "std.replace"

var Std_replace_ArgumentTypes = []value.Type{value.StringType, value.StringType, value.StringType}

func Std_replace_Validate(args []value.Value) error {
	if len(args) != 3 {
		return errors.ArgumentNotEnough(Std_replace_Name, 3, args)
	}
	for i := range args {
		if args[i].Type() != Std_replace_ArgumentTypes[i] {
			return errors.TypeMismatch(Std_replace_Name, i+1, Std_replace_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of std.replace
// Arguments may be:
// - STRING, STRING, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/strings/std-replace/
func Std_replace(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Std_replace_Validate(args); err != nil {
		return value.Null, err
	}

	s := value.GetString(args[0]).String()
	target := value.GetString(args[1]).String()
	replacement := value.GetString(args[2]).String()

	return &value.String{
		Value: strings.Replace(s, target, replacement, 1),
	}, nil
}
