// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

var Subfield_ArgumentTypes = []value.Type{value.StringType, value.StringType, value.StringType}

func Subfield_Validate(args []value.Value) error {
	if len(args) < 2 || len(args) > 3 {
		return errors.ArgumentNotInRange("subfield", 2, 3, args)
	}
	for i := range args {
		if args[i].Type() != Subfield_ArgumentTypes[i] {
			return errors.TypeMismatch("subfield", i+1, Subfield_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of subfield
// Arguments may be:
// - STRING, STRING, STRING
// - STRING, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/miscellaneous/subfield/
func Subfield(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Subfield_Validate(args); err != nil {
		return value.Null, err
	}

	// Need to be implemented
	return value.Null, errors.NotImplemented("subfield")
}
