// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Substr_Name = "substr"

var Substr_ArgumentTypes = []value.Type{value.StringType, value.IntegerType, value.IntegerType}

func Substr_Validate(args []value.Value) error {
	if len(args) < 2 || len(args) > 3 {
		return errors.ArgumentNotInRange(Substr_Name, 2, 3, args)
	}
	for i := range args {
		if args[i].Type() != Substr_ArgumentTypes[i] {
			return errors.TypeMismatch(Substr_Name, i+1, Substr_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of substr
// Arguments may be:
// - STRING, INTEGER, INTEGER
// - STRING, INTEGER
// Reference: https://developer.fastly.com/reference/vcl/functions/strings/substr/
func Substr(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Substr_Validate(args); err != nil {
		return value.Null, err
	}

	// Need to be implemented
	return value.Null, errors.NotImplemented("substr")
}
