// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/ast"
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Table_lookup_integer_Name = "table.lookup_integer"

var Table_lookup_integer_ArgumentTypes = []value.Type{value.IdentType, value.StringType, value.IntegerType}

func Table_lookup_integer_Validate(args []value.Value) error {
	if len(args) != 3 {
		return errors.ArgumentNotEnough(Table_lookup_integer_Name, 3, args)
	}
	for i := range args {
		if args[i].Type() != Table_lookup_integer_ArgumentTypes[i] {
			return errors.TypeMismatch(Table_lookup_integer_Name, i+1, Table_lookup_integer_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of table.lookup_integer
// Arguments may be:
// - TABLE, STRING, INTEGER
// Reference: https://developer.fastly.com/reference/vcl/functions/table/table-lookup-integer/
func Table_lookup_integer(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Table_lookup_integer_Validate(args); err != nil {
		return value.Null, err
	}

	id := value.Unwrap[*value.Ident](args[0]).Value
	key := value.Unwrap[*value.String](args[1]).Value
	defaultValue := value.Unwrap[*value.Integer](args[2])

	table, ok := ctx.Tables[id]
	if !ok {
		return defaultValue, errors.New(Table_lookup_integer_Name,
			"table %d does not exist", id,
		)
	}
	if table.ValueType == nil || table.ValueType.Value != "INTEGER" {
		return defaultValue, errors.New(Table_lookup_integer_Name,
			"table %d value type is not INTEGER", id,
		)
	}

	for _, prop := range table.Properties {
		if prop.Key.Value != key {
			continue
		}
		v, ok := prop.Value.(*ast.Integer)
		if !ok {
			return defaultValue, errors.New(Table_lookup_integer_Name,
				"table %s value could not cast to INTEGER type", id,
			)
		}
		return &value.Integer{Value: v.Value}, nil
	}
	return defaultValue.Copy(), nil
}
