// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"testing"
	// "github.com/ysugimoto/falco/interpreter/context"
	// "github.com/ysugimoto/falco/interpreter/value"
)

// Fastly built-in function testing implementation of table.lookup_acl
// Arguments may be:
// - TABLE, STRING, ACL
// - TABLE, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/table/table-lookup-acl/
func Test_Table_lookup_acl(t *testing.T) {
	t.Skip("Test Builtin function table.lookup_acl should be impelemented")
}
