// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"testing"
	// "github.com/ysugimoto/falco/interpreter/context"
	// "github.com/ysugimoto/falco/interpreter/value"
)

// Fastly built-in function testing implementation of table.lookup_integer
// Arguments may be:
// - TABLE, STRING, INTEGER
// Reference: https://developer.fastly.com/reference/vcl/functions/table/table-lookup-integer/
func Test_Table_lookup_integer(t *testing.T) {
	t.Skip("table.lookup_integer only has difference for table value type")
}
