// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Time_hex_to_time_Name = "time.hex_to_time"

var Time_hex_to_time_ArgumentTypes = []value.Type{value.IntegerType, value.StringType}

func Time_hex_to_time_Validate(args []value.Value) error {
	if len(args) != 2 {
		return errors.ArgumentNotEnough(Time_hex_to_time_Name, 2, args)
	}
	for i := range args {
		if args[i].Type() != Time_hex_to_time_ArgumentTypes[i] {
			return errors.TypeMismatch(Time_hex_to_time_Name, i+1, Time_hex_to_time_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of time.hex_to_time
// Arguments may be:
// - INTEGER, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/date-and-time/time-hex-to-time/
func Time_hex_to_time(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Time_hex_to_time_Validate(args); err != nil {
		return value.Null, err
	}

	// Need to be implemented
	return value.Null, errors.NotImplemented("time.hex_to_time")
}
