// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"testing"
	// "github.com/ysugimoto/falco/interpreter/context"
	// "github.com/ysugimoto/falco/interpreter/value"
)

// Fastly built-in function testing implementation of time.hex_to_time
// Arguments may be:
// - INTEGER, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/date-and-time/time-hex-to-time/
func Test_Time_hex_to_time(t *testing.T) {
	t.Skip("Test Builtin function time.hex_to_time should be impelemented")
}
