// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"fmt"
	"strconv"

	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Time_units_Name = "time.units"

var Time_units_ArgumentTypes = []value.Type{value.StringType, value.TimeType}

func Time_units_Validate(args []value.Value) error {
	if len(args) != 2 {
		return errors.ArgumentNotEnough(Time_units_Name, 2, args)
	}
	for i := range args {
		if args[i].Type() != Time_units_ArgumentTypes[i] {
			return errors.TypeMismatch(Time_units_Name, i+1, Time_units_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of time.units
// Arguments may be:
// - STRING, TIME
// Reference: https://developer.fastly.com/reference/vcl/functions/date-and-time/time-units/
func Time_units(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Time_units_Validate(args); err != nil {
		return value.Null, err
	}

	unit := value.Unwrap[*value.String](args[0]).Value
	t := value.Unwrap[*value.Time](args[1]).Value

	switch unit {
	case "s":
		return &value.String{
			Value: fmt.Sprintf("%d", t.Unix()),
		}, nil
	case "ms":
		v := float64(t.UnixMilli()) / 1000
		return &value.String{
			Value: strconv.FormatFloat(v, 'f', 3, 64),
		}, nil
	case "us":
		v := float64(t.UnixMicro()) / 1000000
		return &value.String{
			Value: strconv.FormatFloat(v, 'f', 6, 64),
		}, nil
	case "ns":
		v := float64(t.UnixNano()) / 1000000000
		return &value.String{
			Value: strconv.FormatFloat(v, 'f', 9, 64),
		}, nil
	default:
		ctx.FastlyError = &value.String{Value: "EINVAL"}
		return &value.String{IsNotSet: true}, errors.New(Time_units_Name,
			"Invalid unit string %s, allow either of s, ms, us and ns", unit,
		)
	}
}
