// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"math"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/ysugimoto/falco/v2/interpreter/context"
	"github.com/ysugimoto/falco/v2/interpreter/value"
)

// Fastly built-in function testing implementation of utf8.substr
// Arguments may be:
// - STRING, INTEGER, INTEGER
// - STRING, INTEGER
// Reference: https://developer.fastly.com/reference/vcl/functions/strings/utf8-substr/
func Test_Utf8_substr(t *testing.T) {
	tests := []struct {
		input      string
		offset     int64
		length     int64
		expect     string
		noLength   bool
		expectNull bool
	}{
		{input: "abあdefg", offset: 3, expect: "defg", noLength: true},
		{input: "abあdefg", offset: 0, length: 2, expect: "ab"},
		{input: "abあdefg", offset: 5, length: 3, expect: "fg"},
		{input: "abあdefg", offset: 5, length: 0, expect: ""},
		{input: "abあ", offset: 4, length: 2, expect: ""},
		{input: "abあ", offset: 3, length: 2, expect: ""},
		{input: "abあdefg", offset: -3, expect: "efg", noLength: true},
		{input: "abあdefg", offset: -3, length: 2, expect: "ef"},
		{input: "abあdefg", offset: 1, length: -3, expect: "bあd"},
		{input: "abあdefg", offset: -4, length: -3, expect: "d"},
		{input: "abあdefg", offset: -4, length: 0, expect: ""},
		{input: "\xe3", offset: 0, length: 1, expectNull: true},
		// Check extremes of length / offset values
		{input: "abあdefg", offset: 2, length: math.MaxInt64 - 1, expect: ""},
		{input: "abあdefg", offset: 1, length: math.MaxInt64, expect: ""},
		{input: "abあdefg", offset: 5, length: -math.MaxInt64, expect: ""},
		{input: "abあdefg", offset: 2, length: -math.MaxInt64 + 1, expect: ""},
		{input: "abあdefg", offset: math.MaxInt64, length: 1, expect: ""},
		{input: "abあdefg", offset: -math.MaxInt64, length: 1, expect: ""},
		{input: "abあdefg", offset: math.MaxInt64, noLength: true, expect: ""},
		{input: "abあdefg", offset: -math.MaxInt64, noLength: true, expect: ""},
		{input: "abあdefg", offset: math.MaxInt64, length: math.MaxInt64, expect: ""},
		{input: "abあdefg", offset: -math.MaxInt64, length: -math.MaxInt64, expect: ""},
		{input: "abあdefg", offset: math.MaxInt64, length: -math.MaxInt64, expect: ""},
		{input: "abあdefg", offset: -math.MaxInt64, length: math.MaxInt64, expect: ""},
	}

	for i, tt := range tests {
		args := []value.Value{
			&value.String{Value: tt.input},
			&value.Integer{Value: tt.offset},
		}
		if !tt.noLength {
			args = append(args, &value.Integer{Value: tt.length})
		}

		ret, err := Utf8_substr(&context.Context{}, args...)
		if err != nil {
			t.Errorf("[%d] Unexpected error: %s", i, err)
			continue
		}
		if tt.expectNull {
			if ret.Type() != value.StringType {
				t.Errorf("[%d] Unexpected return type, expect=STRING, got=%s", i, ret.Type())
				continue
			}
			v := value.Unwrap[*value.String](ret)
			if !v.IsNotSet {
				t.Errorf("[%d] Expected IsNotSet=true, got value=%s", i, v.Value)
			}
			continue
		}
		if ret.Type() != value.StringType {
			t.Errorf("[%d] Unexpected return type, expect=STRING, got=%s", i, ret.Type())
			continue
		}
		v := value.Unwrap[*value.String](ret)
		if v.IsNotSet {
			t.Errorf("[%d] Unexpected return value, expect=%s, got=[not set]", i, tt.expect)
			continue
		}
		if diff := cmp.Diff(tt.expect, v.Value); diff != "" {
			t.Errorf("[%d] Return value unmatch, diff=%s", i, diff)
		}
	}
}
