// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"testing"
	// "github.com/ysugimoto/falco/interpreter/context"
	// "github.com/ysugimoto/falco/interpreter/value"
)

// Fastly built-in function testing implementation of utf8.substr
// Arguments may be:
// - STRING, INTEGER, INTEGER
// - STRING, INTEGER
// Reference: https://developer.fastly.com/reference/vcl/functions/strings/utf8-substr/
func Test_Utf8_substr(t *testing.T) {
	t.Skip("Test Builtin function utf8.substr should be impelemented")
}
