// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"testing"
	// "github.com/ysugimoto/falco/interpreter/context"
	// "github.com/ysugimoto/falco/interpreter/value"
)

// Fastly built-in function testing implementation of uuid.dns
// Arguments may be:
// Reference: https://developer.fastly.com/reference/vcl/functions/uuid/uuid-dns/
func Test_Uuid_dns(t *testing.T) {
	t.Skip("Test Builtin function uuid.dns should be impelemented")
}
