// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

var Uuid_version5_ArgumentTypes = []value.Type{value.StringType, value.StringType}

func Uuid_version5_Validate(args []value.Value) error {
	if len(args) != 2 {
		return errors.ArgumentNotEnough("uuid.version5", 2, args)
	}
	for i := range args {
		if args[i].Type() != Uuid_version5_ArgumentTypes[i] {
			return errors.TypeMismatch("uuid.version5", i+1, Uuid_version5_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of uuid.version5
// Arguments may be:
// - STRING, STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/uuid/uuid-version5/
func Uuid_version5(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Uuid_version5_Validate(args); err != nil {
		return value.Null, err
	}

	// Need to be implemented
	return value.Null, errors.NotImplemented("uuid.version5")
}
