// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"testing"
	// "github.com/ysugimoto/falco/interpreter/context"
	// "github.com/ysugimoto/falco/interpreter/value"
)

// Fastly built-in function testing implementation of uuid.is_version3
// Arguments may be:
// - STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/uuid/uuid-is-version3/
func Test_Uuid_is_version3(t *testing.T) {
	t.Skip("Test Builtin function uuid.is_version3 should be impelemented")
}
