// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"testing"
	// "github.com/ysugimoto/falco/interpreter/context"
	// "github.com/ysugimoto/falco/interpreter/value"
)

// Fastly built-in function testing implementation of uuid.version4
// Arguments may be:
// Reference: https://developer.fastly.com/reference/vcl/functions/uuid/uuid-version4/
func Test_Uuid_version4(t *testing.T) {
	t.Skip("Test Builtin function uuid.version4 should be impelemented")
}
