// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/google/uuid"
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Uuid_x500_Name = "uuid.x500"

var Uuid_x500_ArgumentTypes = []value.Type{}

func Uuid_x500_Validate(args []value.Value) error {
	if len(args) > 0 {
		return errors.ArgumentMustEmpty(Uuid_x500_Name, args)
	}
	return nil
}

// Fastly built-in function implementation of uuid.x500
// Arguments may be:
// Reference: https://developer.fastly.com/reference/vcl/functions/uuid/uuid-x500/
func Uuid_x500(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Uuid_x500_Validate(args); err != nil {
		return value.Null, err
	}

	// URL namespace, namely constant string
	return &value.String{Value: uuid.NameSpaceX500.String()}, nil
}
