// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/function/errors"
	"github.com/ysugimoto/falco/interpreter/function/shared"
	"github.com/ysugimoto/falco/interpreter/value"
)

const Waf_cssDecode_Name = "waf.cssDecode"

var Waf_cssDecode_ArgumentTypes = []value.Type{value.StringType}

func Waf_cssDecode_Validate(args []value.Value) error {
	if len(args) != 1 {
		return errors.ArgumentNotEnough(Waf_cssDecode_Name, 1, args)
	}
	for i := range args {
		if args[i].Type() != Waf_cssDecode_ArgumentTypes[i] {
			return errors.TypeMismatch(Waf_cssDecode_Name, i+1, Waf_cssDecode_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of waf.cssDecode
// Arguments may be:
// - STRING
// Reference:
func Waf_cssDecode(ctx *context.Context, args ...value.Value) (value.Value, error) {
	if err := Waf_cssDecode_Validate(args); err != nil {
		return value.Null, err
	}

	input := value.Unwrap[*value.String](args[0]).Value
	return &value.String{Value: shared.CssDecode(input)}, nil
}
